export const STORIES_DATA = [
{
    "id": "story-01",
    "num": "01",
    "name": "WorkJam Became the Daily Frontline Hub",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Operations Leadership", "HR / Learning", "Store Operations"],
    "secondaryBuyers": ["Store Leadership", "Communications", "Field Leadership"],
    "profile": "Large store footprint; store-based retail workforce",
    "primaryPains": ["Disconnected frontline systems", "Low digital tool adoption", "Fragmented corporate communications"],
    "secondaryPains": ["Inconsistent corporate messaging"],
    "solution": "Make WorkJam the daily starting point for frontline teams.",
    "capabilities": ["Communications", "Tasks", "Learning", "Frontline Hub Experience"],
    "narrative": "Ulta had multiple systems in place, but employees did not have one consistent daily destination. WorkJam became the place associates started their day because it unified operational content, communications, learning, and work actions in one screen. Instead of being a tool employees had to remember to check, WorkJam became the default natural daily hub.",
    "outcomes": ["97% weekly active adoption", "Unified starting hub for thousands of store associates", "Significant boost in voluntary training completion"],
    "whyItMatters": "Adoption is the foundation for every other WorkJam outcome. Once employees actually use the platform every day, the organization can easily drive execution, learning, and scheduling from the exact same operating layer.",
    "demoAngle": "Platform Adoption → Daily Hub → Downstream Execution",
    "demoFit": "Strong",
    "tags": ["adoption", "daily_hub"]
  },
  {
    "id": "story-02",
    "num": "02",
    "name": "On-Time Execution and Labor Savings",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Operations Leadership", "Store Operations", "Field Leadership"],
    "secondaryBuyers": ["Finance", "Labor Planning"],
    "profile": "1,197 stores; 177,000+ tasks analyzed",
    "primaryPains": ["Late task completion / execution timing", "Manager administrative overhead"],
    "secondaryPains": ["Late planograms", "Corporate averages hiding risk"],
    "solution": "Move beyond completion rate and measure whether work is done on time.",
    "capabilities": ["Task Management", "Reporting & Dashboards", "Task Analytics"],
    "narrative": "Ulta saw roughly 99% task completion, which made execution look healthy at a high level. However, WorkJam analytics revealed a deeper problem: nearly half of all tasks were completed late. The work was getting done, but often after the sales or compliance window had closed, creating major wasted opportunities.",
    "outcomes": ["177,000+ store tasks analyzed", "Revealed only 55.7% on-time execution (44% late rate)", "Identified 78,000 late tasks per month", "Discovered ~$530,000 annual labor savings opportunity", "1,200+ manager hours per month potentially recovered"],
    "whyItMatters": "Completion alone can create false confidence. A task completed after the campaign launch or sales window has closed has zero operational value. This story wins when a prospect says, 'We already have a task tool.'",
    "demoAngle": "Completion Rate → On-Time Execution → Labor Savings & Manager Recovery",
    "demoFit": "Extremely Strong",
    "tags": ["roi", "task_management"]
  },
  {
    "id": "story-03",
    "num": "03",
    "name": "Store Variability and Targeted Coaching",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Operations Leadership", "Field Leadership", "District Managers"],
    "secondaryBuyers": ["Store Leadership", "HR"],
    "profile": "1,197-store operating environment",
    "primaryPains": ["Store-to-store execution variability", "Manager administrative overhead"],
    "secondaryPains": ["Field leaders lack diagnostic visibility"],
    "solution": "Use granular WorkJam reporting to identify store-by-store variance and direct targeted coaching.",
    "capabilities": ["Task Management", "Reporting & Dashboards", "Performance Analytics"],
    "narrative": "At the average corporate level, Ulta's execution appeared acceptable. Once broken down by store and district, WorkJam exposed massive operational variance. Some stores executed with absolute precision, while others were failing completely, highlighting localized leadership or routine gaps.",
    "outcomes": ["Identified best store executing at 95% on-time", "Identified worst store executing at less than 1% on-time", "Best district performed at 77% on-time vs. worst district at 22%", "Created a highly precise coaching map for field directors"],
    "whyItMatters": "Execution gaps are rarely cultural; they are usually process, timing, or local coaching gaps. This story reframes analytics from high-level tracking to field-level enablement.",
    "demoAngle": "Analytics → Store Variability → Targeted Coaching Maps",
    "demoFit": "Strong",
    "tags": ["analytics", "coaching"]
  },
  {
    "id": "story-04",
    "num": "04",
    "name": "Task Design and Template Optimization",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Store Operations", "Corporate Operations", "Field Leadership"],
    "secondaryBuyers": ["Labor Planning", "Communications"],
    "profile": "Large store footprint; same workforce executing across categories",
    "primaryPains": ["Late task completion / execution timing", "Manager administrative overhead"],
    "secondaryPains": ["Ineffective planogram compliance"],
    "solution": "Analyze task outcomes strictly by template type to optimize design, layout, timing, and labor alignment.",
    "capabilities": ["Task Management", "Task Templates", "Reporting & Dashboards"],
    "narrative": "WorkJam data showed that the exact same store employees had completely different success rates depending on how tasks were set up. Planograms were almost always late, while vendor sets were completed flawlessly on-time, pointing directly to a template design issue rather than staff work ethic.",
    "outcomes": ["Planograms identified as ~85% late", "Vendor sets identified as ~90% on-time", "Isolated root cause as a task design and timing mismatch", "Allowed immediate remediation of planogram instruction layouts"],
    "whyItMatters": "This is a key story for prospects who automatically assume failure to execute is an employee discipline issue. Correct task design and alignment to labor windows solves execution problems.",
    "demoAngle": "Task Analytics → Root Cause Analysis → Template & Timing Optimization",
    "demoFit": "Strong",
    "tags": ["task_design", "templates"]
  },
  {
    "id": "story-05",
    "num": "05",
    "name": "From Comms Hub to Workforce Orchestration",
    "company": "7-Eleven",
    "industry": "Convenience Retail",
    "primaryBuyers": ["Operations Leadership", "Communications", "Store Operations"],
    "secondaryBuyers": ["HR", "Learning", "Workforce Management"],
    "profile": "Large distributed convenience retail store network",
    "primaryPains": ["Fragmented corporate communications", "Disconnected frontline systems", "Low digital tool adoption"],
    "secondaryPains": ["Difficulty bridging messaging with store actions"],
    "solution": "Evolve WorkJam systematically from communications to unified workforce orchestration.",
    "capabilities": ["Communications", "Surveys", "Training / Learning", "Tasks"],
    "narrative": "7-Eleven leveraged WorkJam to progress through a multi-stage maturity framework. They started with basic, centralized communication, expanded into two-way engagement and voice, integrated structured execution, and prepared the path for unified scheduling.",
    "outcomes": ["Stage 1 Hub: 266,000+ communication post views", "Stage 2 Voice: 42,000+ interactive survey responses", "Stage 3 Alignment: 2,500+ mobile training events executed", "Stage 4 Orchestration: Unified roadmap connecting schedules with operational task execution"],
    "whyItMatters": "Prospects are often overwhelmed by platform size. This case study demonstrates how an enterprise can start with one primary operational pain and expand modularly over time.",
    "demoAngle": "Communications → Engagement → Execution → Full Orchestration",
    "demoFit": "Very Strong",
    "tags": ["maturity_model", "cstore"]
  },
  {
    "id": "story-06",
    "num": "06",
    "name": "Task Failure and Recovery Analysis",
    "company": "City Beach",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Operations Leadership", "Store Operations", "Field Leadership"],
    "secondaryBuyers": ["Communications", "HR"],
    "profile": "77 stores; 19,461 tasks analyzed",
    "primaryPains": ["Late task completion / execution timing", "Manager administrative overhead", "Low digital tool adoption"],
    "secondaryPains": ["Expired work generating waste"],
    "solution": "Apply operational analytics to identify department failure profiles and fix broken templates.",
    "capabilities": ["Task Management", "Reporting & Dashboards", "Task Templates"],
    "narrative": "Only 47% of tasks were being completed overall, with half expiring. However, compliance, VM, and buying tasks had outstanding scores (over 92% completion). The execution drain was highly localized in Store Operations and Retail Ops, where confusing templates and unclear ownership were creating severe friction.",
    "outcomes": ["Analyzed 19,461 store tasks across 77 locations", "Identified that 50% of tasks expired untouched", "Compliance (99%), VM (95%), and Buying (92%) tasks excelled", "Store Ops (29%) and Retail Ops (21%) identified as critical failures", "Saved an estimated 486 wasted manager hours spent chasing expired tasks"],
    "whyItMatters": "If a company believes they have an 'adoption' issue, this proves otherwise: when some departments execute at 99% and others at 21%, it's a layout and instruction problem, not a people problem.",
    "demoAngle": "Low Completion → Root Cause by Workstream → Template Recovery & Layout Fixes",
    "demoFit": "Very Strong",
    "tags": ["task_management", "analytics"]
  },
  {
    "id": "story-07",
    "num": "07",
    "name": "Digital Workplace at Enterprise Scale",
    "company": "Woolworths",
    "industry": "Grocery Retail",
    "primaryBuyers": ["Operations Leadership", "Workforce Management", "IT"],
    "secondaryBuyers": ["HR", "Learning", "Store Operations"],
    "profile": "150,000 live frontline employees",
    "primaryPains": ["Disconnected frontline systems", "Low digital tool adoption", "Manager administrative overhead"],
    "secondaryPains": ["Friction and lines at physical time clocks"],
    "solution": "Converge disparate operational tools into a single primary mobile digital interface.",
    "capabilities": ["Mobile Punching", "Scheduling", "Communications", "Learning"],
    "narrative": "Woolworths consolidated their frontline systems. WorkJam unified access to communications, shifts, and learning into a single mobile dashboard. Mobile geo-fenced punching completely replaced historical congestion and wasted time around legacy physical time clocks.",
    "outcomes": ["Successfully scaled to 150,000 live employees", "Adoption skyrocketed from below 20% to over 80%", "Engineered to seamlessly support 6,000 real-time punches per minute", "Established as one of the single largest digital workplace deployments globally"],
    "whyItMatters": "WorkJam acts as a clean, single convergence layer that sits on top of legacy giants. High adoption rates solve the 'tech fragmentation' pain for IT and Operations alike.",
    "demoAngle": "Convergence → Frictionless Adoption → Enterprise-Grade Scale",
    "demoFit": "Extremely Strong",
    "tags": ["grocery", "adoption", "scale"]
  },
  {
    "id": "story-08",
    "num": "08",
    "name": "Shadow Scheduling and Workforce Signal",
    "company": "Woolworths",
    "industry": "Grocery Retail",
    "primaryBuyers": ["Workforce Management", "Operations Leadership", "Field Leadership"],
    "secondaryBuyers": ["HR", "Store Leadership", "Labor Planning"],
    "profile": "Large scale grocery retail workforce",
    "primaryPains": ["Labor shortages & shift coverage friction", "Disconnected frontline systems", "Manager administrative overhead"],
    "secondaryPains": ["Unregulated schedule swaps via unofficial WhatsApp groups"],
    "solution": "Transition scheduling communication into a structured, compliance-friendly mobile workflow.",
    "capabilities": ["Scheduling", "Direct Messaging", "Open Shift Workflows", "Surveys"],
    "narrative": "Woolworths uncovered that employees were heavily utilizing chat systems to negotiate schedules outside of their standard WFM system. By routing schedule discussions through WorkJam's compliant interface, leadership instantly gained visibility into shifts that needed coverage and real employee sentiment.",
    "outcomes": ["Tracked 75,656 weekly direct messages; discovered 22.7% were strictly scheduling-related", "Identified that 10% of shifts routinely sat unfilled", "Revealed massive preference signal: 51% of part-timers desired 24+ weekly hours", "Logged a 93% positive frontline sentiment, with 30% of posts focused on recognition"],
    "whyItMatters": "Legacy WFM systems are only systems of record—not engagement. When you bring schedule communication into WorkJam, you stop 'shadow scheduling' and gain raw data on true labor capacity.",
    "demoAngle": "Shadow Work Discovery → Real Labor Signal → Compliant Shift Workflows",
    "demoFit": "Very Strong",
    "tags": ["shadow_work", "scheduling"]
  },
  {
    "id": "story-09",
    "num": "09",
    "name": "Engagement Without Execution Gap",
    "company": "KIKO",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Communications", "Operations Leadership", "Store Operations"],
    "secondaryBuyers": ["Field Leadership", "HR"],
    "profile": "Distributed global beauty cosmetics retail workforce",
    "primaryPains": ["Fragmented corporate communications", "Late task completion / execution timing"],
    "secondaryPains": ["High communication read rates with zero corresponding store action"],
    "solution": "Directly link marketing and operations communications with actionable, trackable task workflows.",
    "capabilities": ["Communications", "Task Management", "Campaigns", "Reporting"],
    "narrative": "KIKO store associates loved reading internal newsletters and liking corporate posts, but they weren't actually setting up the corresponding promotional counters. WorkJam closed this loop by attaching specific, trackable, and timed tasks directly underneath corporate posts.",
    "outcomes": ["Achieved high 84% positive engagement and love reactions", "Identified critical execution gap: only 55% of tasks got done, 45% expired", "Successfully merged communication campaigns with task modules to drive accountability"],
    "whyItMatters": "Social tools or standard intranets measure 'reads' and 'likes' but cannot prove if product displays were actually set up. WorkJam turns communication into measurable execution.",
    "demoAngle": "Communication Intranet Limits → Execution Gap → Task-Integrated Campaigns",
    "demoFit": "Strong",
    "tags": ["communication", "engagement"]
  },
  {
    "id": "story-10",
    "num": "10",
    "name": "Operations and Retention Engine",
    "company": "Young Guns",
    "industry": "Logistics",
    "primaryBuyers": ["Operations Leadership", "HR", "Field Leadership"],
    "secondaryBuyers": ["Communications", "Workforce Planning"],
    "profile": "Highly distributed, mobile-first blue-collar teams",
    "primaryPains": ["Frontline staff turnover & engagement", "Fragmented corporate communications", "Manager administrative overhead"],
    "secondaryPains": ["No early warning system for workers on the verge of quitting"],
    "solution": "Use WorkJam channels and interactive sentiment tools as an operational retention engine.",
    "capabilities": ["Channels", "Communities", "Direct Messaging", "Sentiment Analysis"],
    "narrative": "Operating a physical, fast-paced logistics business, Young Guns utilized WorkJam to send schedules, coordinate dispatch, and foster community. They monitored active messaging to identify early warning patterns (such as workers repeatedly asking 'do I have shifts next week?') to intervene before they quit.",
    "outcomes": ["Drove 120,000+ active operational messages & 73,000+ targeted nudges", "Maintained a strong 70% favorability rating across a high-turnover industry", "Identified critical sentiment metrics: Recognition signal at 66%, voice signal at 67%"],
    "whyItMatters": "In hourly work, a text like 'When do I start?' or 'Am I working?' is actually an early-warning retention risk. Catching these questions inside a managed system prevents no-shows and quits.",
    "demoAngle": "Operational Chats → Sentiment Analytics → Dropout & No-Show Prevention",
    "demoFit": "Strong",
    "tags": ["engagement", "retention"]
  },
  {
    "id": "story-11",
    "num": "11",
    "name": "Signal-to-Noise Reduction at Scale",
    "company": "Metro AG",
    "industry": "Wholesale Retail",
    "primaryBuyers": ["Operations Leadership", "IT / Digital Transformation"],
    "secondaryBuyers": ["HR / Learning", "Field Leadership"],
    "profile": "95,000 employees; 650 stores across 30 countries",
    "primaryPains": ["Fragmented corporate communications", "Disconnected frontline systems", "Late task completion / execution timing"],
    "secondaryPains": ["Too many legacy systems for managers to log into"],
    "solution": "Leverage Task Connect to isolate critical operational signals from general chatter.",
    "capabilities": ["Task Management", "Task Connect", "Communications", "Integrations"],
    "narrative": "Metro AG faced extreme information overload across 30 countries. Tasks were being sent out via legacy email chains and standard chats, leading to operational chaos. WorkJam acted as an intelligent filter, pushing tasks exclusively to the relevant employee on shift, and automatically syncing completions to back-end ERP systems.",
    "outcomes": ["Drastically reduced global operational noise in 650 hypermarkets", "Abolished role-irrelevant broadcast alerts for store staff", "Seamlessly integrated execution with backend ERP databases"],
    "whyItMatters": "To drive productivity, you must stop sending everything to everyone. WorkJam is the smart routing layer that delivers targeted, role-based tasks, and feeds execution data back into legacy systems.",
    "demoAngle": "Operational Noise → Role-Targeted Workflows → Seamless ERP Sync",
    "demoFit": "Strong",
    "tags": ["signal_vs_noise", "integration"]
  },
  {
    "id": "story-12",
    "num": "12",
    "name": "Execution and Compliance Confidence",
    "company": "Marks & Spencer",
    "industry": "Grocery Retail",
    "primaryBuyers": ["Operations Leadership", "Compliance", "Store Operations"],
    "secondaryBuyers": ["HR / Learning", "Field Leadership"],
    "profile": "65,000 employees; 650 multi-department stores",
    "primaryPains": ["Compliance & food safety / product recall risk", "Late task completion / execution timing", "Manager administrative overhead"],
    "secondaryPains": ["Slow response times during high-risk recall alerts"],
    "solution": "Consolidate vital compliance procedures, recalls, and role training into a single platform.",
    "capabilities": ["Task Management", "Learning", "Communications", "Reporting & Dashboards"],
    "narrative": "Marks & Spencer needed to ensure regulatory compliance across food safety and apparel. Instead of manual phone trees and sign-off sheets, they digitized emergency 'Red Alerts' (e.g., immediate product recalls) inside WorkJam, allowing headquarters to watch completions roll in live across the country.",
    "outcomes": ["Achieved a masterclass 97% general task completion rate", "Secured 100% compliance rate on critical safety Red Alerts", "Substantially reduced execution and response times during product recalls"],
    "whyItMatters": "For operations, legal, and compliance buyers, speed and verified tracking are mandatory. This story provides massive piece of mind to risk-sensitive prospects.",
    "demoAngle": "Compliance Risk Event → Targeted Push → 100% Execution Proof",
    "demoFit": "Very Strong",
    "tags": ["compliance", "recalls"]
  },
  {
    "id": "story-13",
    "num": "13",
    "name": "Global Training & $5.5M LMS Savings",
    "company": "Shell",
    "industry": "Fuel & Convenience",
    "primaryBuyers": ["Operations Leadership", "Global Learning & Development"],
    "secondaryBuyers": ["IT", "Compliance", "Franchise Operations"],
    "profile": "500,000 frontline associates globally",
    "primaryPains": ["LMS costs & training completion", "Disconnected frontline systems", "Compliance & food safety / product recall risk"],
    "secondaryPains": ["Excessive licensing overhead across 14 separate LMS tools"],
    "solution": "Consolidate 14 legacy LMS portals into one, unified mobile-first frontline experience.",
    "capabilities": ["Learning & Assessments", "Communications", "Badging & Rewards"],
    "narrative": "Shell operated in an incredibly complex global environment with hundreds of franchise partners and 14 legacy training systems. Moving training to WorkJam put micro-learnings directly into the daily flow of work, dramatically lowering friction and licensing costs while boosting safety pass rates.",
    "outcomes": ["Delivered a massive $5.5 Million in annual LMS licensing cost savings", "Drove a stellar 63% reduction in global retail safety incidents", "Boosted regulatory compliance training completion from 63% to 80%"],
    "whyItMatters": "This is a cornerstone ROI case study. It proves that consolidating software saves millions while concurrently improving frontline safety metrics.",
    "demoAngle": "Global LMS Mess → Mobile micro-learning → Massive ROI & Safety Lift",
    "demoFit": "Extremely Strong",
    "tags": ["training", "roi"]
  },
  {
    "id": "story-14",
    "num": "14",
    "name": "Multi-Division Execution Optimization",
    "company": "Midcounties Co-op",
    "industry": "Multi-Division",
    "primaryBuyers": ["Operations Leadership", "Field Leadership"],
    "secondaryBuyers": ["HR", "IT"],
    "profile": "8,000 frontline employees across multiple distinct business divisions",
    "primaryPains": ["Manager administrative overhead", "Disconnected frontline systems", "Store-to-store execution variability"],
    "secondaryPains": ["Different business units operating with entirely separate tools"],
    "solution": "Deploy WorkJam as an overarching operations layer to unify communication and standard tasks.",
    "capabilities": ["Task Management", "Communications", "Surveys", "ServiceNow Integrations"],
    "narrative": "With business lines ranging from grocery stores to travel agencies, Midcounties Co-op suffered from extreme operational fragmentation. WorkJam united these distinct business units under one common user experience, helping general managers save hours of administrative overhead every single week.",
    "outcomes": ["Achieved a spectacular 90%+ frontline adoption in only 10 weeks", "Drove a 40% speed improvement in task completion times", "Saved managers an average of 4 hours per week, allowing more time with customers"],
    "whyItMatters": "For complex conglomerates, WorkJam provides a single digital identity and standard operating interface, eliminating multi-tool licensing and administrative fatigue.",
    "demoAngle": "Multi-Division Complexity → Digital Standard → Manager Time Recovery",
    "demoFit": "Strong",
    "tags": ["multi_division", "adoption"]
  },
  {
    "id": "story-15",
    "num": "15",
    "name": "Feedback to CX Remediation",
    "company": "Circle K",
    "industry": "Convenience Retail",
    "primaryBuyers": ["Operations Leadership", "Customer Experience"],
    "secondaryBuyers": ["IT", "Store Operations"],
    "profile": "High-volume, fast-paced convenience store environments",
    "primaryPains": ["Late task completion / execution timing", "Store-to-store execution variability"],
    "secondaryPains": ["Customer complaints sitting in dashboards with zero store action"],
    "solution": "Convert real-time customer survey alerts directly into actionable, trackable store cleanup and inventory tasks inside WorkJam.",
    "capabilities": ["Surveys", "Task Management", "Scheduling / Workflows"],
    "narrative": "Circle K received thousands of customer surveys but struggled to operationalize the complaints. If a customer flagged a dirty coffee station or an out-of-stock item, it lived in a distant corporate report. With WorkJam, low survey scores trigger an immediate, high-priority remediation task for the shift team.",
    "outcomes": ["Established instant, automated loop from negative customer feedback to store task", "Vastly improved store cleanliness and stock standard execution times", "Created digital accountability for store managers on localized CX scores"],
    "whyItMatters": "Most CX platforms only diagnose problems. WorkJam actually closes the feedback loop by turning insights into physical tasks for immediate store resolution.",
    "demoAngle": "CX Survey Feedback → Dynamic Task Generation → Verifiable Remediation",
    "demoFit": "Strong",
    "tags": ["cstore", "cx"]
  },
  {
    "id": "story-16",
    "num": "16",
    "name": "Inventory Execution & Labor Flexibility",
    "company": "American Eagle",
    "industry": "Apparel Retail",
    "primaryBuyers": ["Operations Leadership", "Store Operations"],
    "secondaryBuyers": ["Supply Chain", "Workforce Management"],
    "profile": "Fast-fashion specialty store retail workforce",
    "primaryPains": ["Labor shortages & shift coverage friction", "Late task completion / execution timing"],
    "secondaryPains": ["Extreme inventory inaccuracy due to delayed or late physical counts"],
    "solution": "Coordinate inventory execution tasks in unison with WorkJam's Open Shift Marketplace.",
    "capabilities": ["Task Management", "Open Shift Marketplace", "Scheduling"],
    "narrative": "American Eagle had to perform massive physical audits but lacked sufficient staffing at critical sites. By using WorkJam, they pushed step-by-step physical inventory tasks to stores, while simultaneously utilizing the Open Shift Marketplace to allow qualified nearby employees to pick up extra audit shifts.",
    "outcomes": ["Completed 1,100 full cycle inventories in just 8 days", "Achieved record-breaking inventory velocity with flawless data accuracy", "Significantly reduced labor gaps by letting store staff grab shifts at sister branches"],
    "whyItMatters": "This is the ultimate bridge between execution and labor capacity. It answers the question: 'How do I get important work done when a specific store is short-staffed?'",
    "demoAngle": "Heavy Inventory Tasks + Cross-Store Labor Sharing = Hyper-Velocity Audit",
    "demoFit": "Strong",
    "tags": ["apparel", "inventory"]
  },
  {
    "id": "story-17",
    "num": "17",
    "name": "Adoption and Shift Marketplace Impact",
    "company": "JCPenney",
    "industry": "Department Store",
    "primaryBuyers": ["Operations Leadership", "HR", "Workforce Management"],
    "secondaryBuyers": ["IT", "Store Operations"],
    "profile": "Large-scale national department store chain",
    "primaryPains": ["Low digital tool adoption", "Labor shortages & shift coverage friction", "Fragmented corporate communications"],
    "secondaryPains": ["Low application download rates across legacy systems"],
    "solution": "Dangle shift flexibility and open scheduling as the core carrot to drive mass adoption of WorkJam.",
    "capabilities": ["Communications", "Open Shift Marketplace", "Scheduling"],
    "narrative": "JCPenney wanted to update frontline communications but struggled to get employees to adopt standard intranet tools. By introducing the Open Shift Marketplace on WorkJam, associates flocked to the platform to gain control over their hours, providing corporate with an engaged audience.",
    "outcomes": ["Achieved a massive 97% voluntary digital platform adoption", "Filled 5,000+ shifts seamlessly without manual manager outreach", "Drove a stellar 3x increase in employee hiring referrals"],
    "whyItMatters": "Frontline workers will not download an app simply because corporate wants to send news. They will download it if it gives them control over their paychecks. The adoption follows the value.",
    "demoAngle": "Schedule Control Carrot → Mass Adoption → Seamless Corporate Messaging",
    "demoFit": "Strong",
    "tags": ["department_store", "adoption"]
  },
  {
    "id": "story-18",
    "num": "18",
    "name": "Open Shift Marketplace and Speed",
    "company": "Team Washington",
    "industry": "Franchise / QSR",
    "primaryBuyers": ["Operations Leadership", "Workforce Management"],
    "secondaryBuyers": ["Franchise Owners", "Restaurant Leadership"],
    "profile": "Franchise-owned pizza restaurant and driver network",
    "primaryPains": ["Labor shortages & shift coverage friction", "Manager administrative overhead"],
    "secondaryPains": ["High service delivery delays due to short-staffed shifts"],
    "solution": "Implement peer-to-peer open shift exchanges with rule boundaries to eliminate manager schedule administration.",
    "capabilities": ["Open Shift Marketplace", "Scheduling"],
    "narrative": "Operating a quick-service delivery model, Team Washington suffered from unexpected staffing bottlenecks. By utilizing WorkJam's Open Shift Marketplace, peer restaurant workers easily swapped coverage shifts amongst themselves without taxing managers.",
    "outcomes": ["Slashed manager administrative workload and scheduling phone-calls", "Drove a direct 6-minute improvement in average home delivery times", "Significantly stabilized restaurant staffing ratios during peak weekend rushes"],
    "whyItMatters": "In QSR, seconds equal dollars. By reducing shift-coverage friction, managers run tighter shifts, directly impacting delivery speed and customer satisfaction.",
    "demoAngle": "Self-Service Scheduling → Better Staffing Levels → Faster Speed-of-Service",
    "demoFit": "Strong",
    "tags": ["qsr", "open_shift_marketplace"]
  },
  {
    "id": "story-19",
    "num": "19",
    "name": "Internal Gig Workforce Flexibility",
    "company": "Domino's",
    "industry": "Franchise / QSR",
    "primaryBuyers": ["Operations Leadership", "Workforce Management", "Franchise Operations"],
    "secondaryBuyers": ["Restaurant Leadership", "HR"],
    "profile": "High-velocity store and delivery driver workforce",
    "primaryPains": ["Frontline staff turnover & engagement", "Labor shortages & shift coverage friction"],
    "secondaryPains": ["Drivers leaving to work for gig platforms like Uber & DoorDash"],
    "solution": "Counter gig economy platforms by offering internal shift flexibility across local store clusters on WorkJam.",
    "capabilities": ["Open Shift Marketplace", "Scheduling", "Communications"],
    "narrative": "Domino's was bleeding delivery drivers to external food-delivery apps that promised total schedule autonomy. To fight back, Domino's used WorkJam to build an 'Internal Gig Network,' allowing drivers to instantly pick up shifts across multiple regional locations.",
    "outcomes": ["Successfully countered external gig apps by offering comparable scheduling flexibility", "Drastically improved shift fill-rates across clustered franchise zones", "Reduced hiring and onboarding costs by retaining existing drivers in the network"],
    "whyItMatters": "You do not have to lose staff to Uber. By allowing your own employees to work across sister locations via WorkJam, you maximize internal capacity and retain your talent.",
    "demoAngle": "Fighting Gig Apps with Gig Flexibility → Clustered Store Labor Pools",
    "demoFit": "Strong",
    "tags": ["qsr", "gig_workforce"]
  },
  {
    "id": "story-20",
    "num": "20",
    "name": "Engagement Drives Execution Correlation",
    "company": "Panda Express",
    "industry": "Franchise / QSR",
    "primaryBuyers": ["Operations Leadership", "Field Leadership", "HR"],
    "secondaryBuyers": ["Communications", "Restaurant Leadership"],
    "profile": "Distributed fast-casual restaurant workforce",
    "primaryPains": ["Store-to-store execution variability", "Frontline staff turnover & engagement"],
    "secondaryPains": ["No clear proof that communication drive real restaurant operations"],
    "solution": "Pair communication engagement signals and task execution metrics together to build clear store coaching typologies.",
    "capabilities": ["Communications", "Task Management", "Reporting & Dashboards"],
    "narrative": "Panda Express wanted to analyze whether strong internal communications truly impacted restaurant execution. Using WorkJam analytics, they proved that highly active communicative managers ran significantly higher-performing store execution modules.",
    "outcomes": ["Achieved consistent 92%+ task completion rates across participating sites", "Enabled clear performance segmentation maps for field directors", "Correlated high digital engagement with direct restaurant sales and hygiene execution"],
    "whyItMatters": "This case study elevates internal communication from a 'soft' metric to a key predictor of execution. Engaged managers drive better restaurants, and WorkJam proves it.",
    "demoAngle": "Engagement Signals + Execution Metrics = Precision Store Segmentation",
    "demoFit": "Strong",
    "tags": ["qsr", "engagement"]
  },
  {
    "id": "story-21",
    "num": "21",
    "name": "Urgent Recall Communication at Scale",
    "company": "Grocery Retail Use Case",
    "industry": "Grocery Retail",
    "primaryBuyers": ["Operations Leadership", "Compliance", "Food Safety"],
    "secondaryBuyers": ["Store Operations", "Communications", "Field Leadership"],
    "profile": "Large grocery store workforce",
    "primaryPains": ["Compliance & food safety / product recall risk", "Late task completion / execution timing"],
    "secondaryPains": ["Sloppy manual cascades during recalls"],
    "solution": "Turn high-risk recall alerts into mandatory, geo-targeted, and trackable micro-tasks.",
    "capabilities": ["Communications", "Task Management", "Reporting"],
    "narrative": "In grocery retail, an infected food batch requires instantaneous action. Rather than relying on phone cascades, grocery operators use WorkJam to send an emergency 'Recall Task' with photo verification required, ensuring dangerous inventory is pulled from shelves instantly.",
    "outcomes": ["Replaced slow corporate cascades with automated, instant recall delivery", "Secured ironclad compliance verification down to the specific store shift", "Provided compliance boards with absolute audit trails of safety operations"],
    "whyItMatters": "In food-safety, there is no margin for error. Sending a message is not enough—proving execution is what protects the brand from massive legal liabilities.",
    "demoAngle": "Emergency Recall → Instant Targeted Task Push → Mandatory Photo Proof Verification",
    "demoFit": "Strong",
    "tags": ["grocery", "compliance"]
  },
  {
    "id": "story-22",
    "num": "22",
    "name": "Record-Breaking Plant Adoption",
    "company": "General Motors",
    "industry": "Manufacturing",
    "primaryBuyers": ["Manufacturing Operations", "Communications", "HR / Employee Experience"],
    "secondaryBuyers": ["IT", "Plant Leadership"],
    "profile": "U.S. hourly manufacturing workforce; 26 plants in 2026 rollout",
    "primaryPains": ["Low digital tool adoption", "Fragmented corporate communications"],
    "secondaryPains": ["Historically miserable adoption of digital tools among hourly union workers"],
    "solution": "Build a highly structured, localized, and event-focused launch playbook to secure union trust.",
    "capabilities": ["Communications", "Channels", "Surveys", "Launch Strategy"],
    "narrative": "Historically, GM's manufacturing union employees ignored corporate apps, showing only ~10% adoption in legacy pilots. To resolve this, GM launched WorkJam via a tailored, localized, plant-specific rollout playbook. They combined local site champion teams and custom QR codes to drive registration.",
    "outcomes": ["26 major manufacturing plants successfully mapped to the 2026 path", "Achieved 29% combined adoption across plants within initial weeks", "Tripled historical engagement, lifting adoption 3x versus previous pilots", "Bedford plant achieved a record 47% voluntary union employee adoption"],
    "whyItMatters": "Hourly union workers are notoriously difficult to engage. This story proves that with a structured, plant-centric rollout strategy, WorkJam can break through historical resistance.",
    "demoAngle": "Legacy Pilot Failures → Event-Driven Launch Playbook → 3x Adoption Lift",
    "demoFit": "Very Strong",
    "tags": ["gm", "manufacturing"]
  },
  {
    "id": "story-23",
    "num": "23",
    "name": "Daily Engagement & Stickiness Strategy",
    "company": "General Motors",
    "industry": "Manufacturing",
    "primaryBuyers": ["Communications", "HR / Employee Experience", "Manufacturing Operations"],
    "secondaryBuyers": ["Plant Leadership", "IT"],
    "profile": "Hourly manufacturing employees across rollout plants",
    "primaryPains": ["Low digital tool adoption", "Fragmented corporate communications"],
    "secondaryPains": ["Post-launch usage drop-off; getting users to return daily"],
    "solution": "Transform the mobile app from a corporate megaphone into an invaluable local bulletin board.",
    "capabilities": ["Communications", "Channels", "Surveys"],
    "narrative": "Getting workers to sign up is only half the battle. To drive permanent stickiness, GM pivoted content creation from high-level corporate bulletins to highly localized plant news. Things like shift schedules, food truck calendars, and local plant highlights kept workers coming back.",
    "outcomes": ["Bedford and LDT plants sustained an outstanding ~50% Daily Active User (DAU) rate", "Lifted daily return rates by 10 to 20 percentage points over standard pilots", "Established WorkJam as a persistent frontline routine rather than a single-use app"],
    "whyItMatters": "Frontline stickiness only happens when the content is locally relevant. If an app only displays corporate CEO letters, users uninstall it. Localized plant utility drives daily return.",
    "demoAngle": "Initial Sign-ups → Localized Plant Content → Sustained 50% DAU Stickiness",
    "demoFit": "Strong",
    "tags": ["gm", "engagement"]
  },
  {
    "id": "story-24",
    "num": "24",
    "name": "Enterprise Demand Signal Growth",
    "company": "General Motors",
    "industry": "Manufacturing",
    "primaryBuyers": ["Enterprise Operations", "Communications", "IT"],
    "secondaryBuyers": ["HR", "Safety", "CCA"],
    "profile": "Global manufacturing enterprise with massive cross-functional demand",
    "primaryPains": ["Disconnected frontline systems", "Manager administrative overhead"],
    "secondaryPains": ["Different corporate divisions requesting separate single-purpose apps"],
    "solution": "Capitalize on initial communications success to position WorkJam as the primary frontline standard.",
    "capabilities": ["Communications", "Channels", "Digital Workplace Hub"],
    "narrative": "As plant communications flourished, other business divisions within GM witnessed the high adoption rates and began requesting space on the platform. Demand exploded from global teams, customer care, and safety compliance, changing the system's reputation from a 'comms app' into an enterprise engine.",
    "outcomes": ["26 U.S. manufacturing plants now actively pull in new capabilities", "Expanded demand to regional global territories and Customer Care (CCA)", "Triggered integration tracks for UKG, HCC legacy replacement, and safety logs", "Evolved WorkJam from a messaging tool into GM's primary frontline operating layer"],
    "whyItMatters": "Internal pull and word-of-mouth are the ultimate validation of software. When regional managers are begging for rollouts, IT departments avoid duplicate licensing.",
    "demoAngle": "Messaging Project → Explosion of Cross-Functional Demand → Unified Standard Layer",
    "demoFit": "Very Strong",
    "tags": ["gm", "expansion"]
  },
  {
    "id": "story-25",
    "num": "25",
    "name": "Single Pane of Glass Tool Consolidation",
    "company": "General Motors",
    "industry": "Manufacturing",
    "primaryBuyers": ["IT", "Enterprise Operations", "Executive Leadership"],
    "secondaryBuyers": ["Communications", "HR"],
    "profile": "Hourly manufacturing workforce",
    "primaryPains": ["Disconnected frontline systems", "Low digital tool adoption"],
    "secondaryPains": ["Shadow IT and unmanaged consumer messaging apps running wild"],
    "solution": "Enforce strict IT guiding principles to mandate WorkJam as the single entry point.",
    "capabilities": ["Communications", "Channels", "Digital Workplace Hub"],
    "narrative": "To stop shadow applications and rising software expenses, GM's leadership enacted strict IT principles: employees are at the core, we construct a 'single pane of glass,' and we integrate rather than purchase duplicate single-purpose apps.",
    "outcomes": ["Deployed WorkJam as the master 'Single Pane of Glass' for the hourly workforce", "Successfully blocked the introduction of rogue shadow messaging applications", "Established clear platform governance, streamlining future funding and support paths"],
    "whyItMatters": "IT leaders love this case study. It establishes a clear, unified governance framework that controls software spend, keeps compliance high, and simplifies the user experience.",
    "demoAngle": "Frontline Tool Sprawl → Single Pane of Glass Governance → Zero Shadow IT",
    "demoFit": "Very Strong",
    "tags": ["gm", "consolidation"]
  },
  {
    "id": "story-26",
    "num": "26",
    "name": "Store Variability & Precision Coaching",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Field Leadership", "Regional Managers"],
    "secondaryBuyers": ["Operations Leadership", "HR / Learning"],
    "profile": "1,197 stores; multi-tiered field leadership hierarchy",
    "primaryPains": ["Store-to-store execution variability", "Manager administrative overhead"],
    "secondaryPains": ["Poorly performing stores hidden behind gorgeous regional averages"],
    "solution": "Break down completion data by store and district to build precise coaching maps.",
    "capabilities": ["Task Management", "Reporting", "Store / District Analytics"],
    "narrative": "By utilizing WorkJam's store-by-store performance segmentation, Ulta discovered that overall high average completion scores were masking massive local deficiencies, enabling field leaders to step in and fix specific store issues.",
    "outcomes": ["Isolated the best-performing store executing at 95.4% on-time", "Exposed the worst-performing store executing at an abysmal 0.7% on-time", "Mapped the top district (77.1% on-time) and the bottom district (22.7% on-time)", "Replaced random, generic store checks with data-driven operational visits"],
    "whyItMatters": "Average scores create blindspots. Uncovering that a store is operating at 0.7% on-time task execution allows regional leaders to conduct diagnostic interventions before store sales drop.",
    "demoAngle": "High Highs, Low Lows → Unmasking Averages → Precision Field Coaching",
    "demoFit": "Strong",
    "tags": ["coaching", "store_variability"]
  },
  {
    "id": "story-27",
    "num": "27",
    "name": "Task Design Operational Friction Mapping",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Operations Leadership", "Process Owners"],
    "secondaryBuyers": ["Field Leadership", "Store Ops"],
    "profile": "Same store associate workforce executing across multiple work categories",
    "primaryPains": ["Late task completion / execution timing", "Manager administrative overhead"],
    "secondaryPains": ["Low visual planogram compliance causing poor sales"],
    "solution": "Analyze execution data specifically by task template to isolate and redesign bad instructions.",
    "capabilities": ["Task Management", "Templates", "Analytics"],
    "narrative": "Ulta utilized WorkJam to review task completions by department. They found that store employees executed vendor setups beautifully on-time, but planograms were chronically late, proving the problem lay in complex planogram designs and timing.",
    "outcomes": ["Planogram resets logged as ~88% late", "Planogram updates logged as ~86% late", "Vendor-supplied tasks logged at an exceptional ~90% on-time completion", "Shifted corporate focus from employee discipline to template instruction optimization"],
    "whyItMatters": "If your team is completing one task type perfectly and failing another, it's not a motivational issue—the instructions or allocated hours are broken. WorkJam diagnoses the blueprint.",
    "demoAngle": "Task Typology Performance → Structural Design vs Motivation → UI Remediation",
    "demoFit": "Strong",
    "tags": ["task_design", "templates"]
  },
  {
    "id": "story-28",
    "num": "28",
    "name": "Engagement Drives Execution at Scale",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Operations Leadership", "Communications"],
    "secondaryBuyers": ["Field Leadership", "HR"],
    "profile": "1,395 active stores; 930 highly engaged locations analyzed",
    "primaryPains": ["Store-to-store execution variability", "Fragmented corporate communications"],
    "secondaryPains": ["Inability to prove that social interactions affect physical business outcomes"],
    "solution": "Segment stores by digital engagement to scientifically prove the link to completion.",
    "capabilities": ["Channels", "Reactions", "Comments", "Store Typology Analytics"],
    "narrative": "Ulta divided stores into distinct operational profiles based on their WorkJam activity. The analysis proved that stores with high digital participation, comment activity, and communication engagement executed operations with superior speed and quality.",
    "outcomes": ["Proved that high-engagement stores complete 3.2 percentage points more operational tasks", "Identified and classified 488 perfect Model Stores", "Segmented 162 Coaching Opportunity, 442 Quiet Effective, and 303 At-Risk Stores", "Logged highly positive 81% overall sentiment across 22,114 store comments"],
    "whyItMatters": "This is the ultimate scientific proof that communication is not 'soft.' Highly communicative managers create highly execution-capable frontline teams.",
    "demoAngle": "Social Signals → Store Typology Segments → Direct Task-Completion Lift",
    "demoFit": "Very Strong",
    "tags": ["engagement", "execution"]
  },
  {
    "id": "story-29",
    "num": "29",
    "name": "Scheduling as Execution Intelligence",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["Workforce Management", "Operations Leadership"],
    "secondaryBuyers": ["HR", "Field Leadership"],
    "profile": "1,518 stores; 55,896 associates; 226,505 shifts analyzed",
    "primaryPains": ["Labor shortages & shift coverage friction", "Late task completion / execution timing"],
    "secondaryPains": ["Disconnect between labor availability and heavy task deadlines"],
    "solution": "Integrate schedule shifts directly with task schedules to transform scheduling into operational metrics.",
    "capabilities": ["Scheduling", "Task Management", "Workforce Analytics"],
    "narrative": "Ulta analyzed scheduling data inside WorkJam and proved that execution backlogs were directly caused by shift structures. Sunday shifts contained peak labor allocations but lacked targeted task structures to clear backlogs before Monday morning.",
    "outcomes": ["Value: Sunday captured 24.9% of total weekly labor allocation", "Selling + Task roles made up 48.4% of total retail hours", "Used schedule telemetry to optimize task drops to occur during peak staffed shifts", "Analyzed 226,505 distinct shift touchpoints and 1.38 Million labor hours"],
    "whyItMatters": "Scheduling is not just about coverage—it is about execution capability. Aligning your task drops directly to your peak shift coverage ensures tasks are completed quickly.",
    "demoAngle": "Labor Data Telemetry → Task Drop Alignment → Massive Backlog Elimination",
    "demoFit": "Strong",
    "tags": ["wfm", "scheduling"]
  },
  {
    "id": "story-30",
    "num": "30",
    "name": "Digital Workplace Compliance Habit",
    "company": "Ulta Beauty",
    "industry": "Specialty Retail",
    "primaryBuyers": ["HR", "Compliance", "Operations Leadership"],
    "secondaryBuyers": ["Store Leadership"],
    "profile": "59,958 employees; 1,653 locations",
    "primaryPains": ["Compliance & food safety / product recall risk", "Low digital tool adoption"],
    "secondaryPains": ["State-specific compliance gaps (CA/IL)"],
    "solution": "Embed digital compliance sign-offs directly inside the daily mobile routine.",
    "capabilities": ["Surveys", "Compliance Tracking", "Reporting"],
    "narrative": "Ulta leveraged WorkJam to execute state-mandated workplace and compliance agreements. By embedding the digital agreement process into the mobile frontline app, associates signed off on their shifts in seconds, with automated reminders handling non-compliant staff.",
    "outcomes": ["Achieved an outstanding 88.9% overall digital compliance completion", "Reached an exemplary 96.9% manager-level compliance completion", "Secured 93.3% compliance for specialized CA and IL enhanced labor regulations", "Tracked and isolated a critical Week-9 compliance dip for immediate training"],
    "whyItMatters": "Workplace compliance can create massive legal exposure if unmanaged. Moving sign-offs into WorkJam's daily flow makes compliance seamless and provides instant auditing protection.",
    "demoAngle": "Daily Frontline Habits → Digital Compliance Sign-off → Legal Security",
    "demoFit": "Strong",
    "tags": ["compliance", "habit_formation"]
  }
]
